name: pytorch
channels:
  - defaults
dependencies:
  - python=3.10.12
  - pytorch
  - pytorch-cuda=11.8
  - torchaudio
  - torchtext
  - torchvision
  - conda
  - jupyter
  - matplotlib
  - spacy
  - pandas
